version: "3"

services:
    redis:
        image: redis
    gqlgen:
        image: localhost:5000/mitsuyoshi4/graphql-chat
        ports:
            - "8080:8080"
        environment:
            - REDIS_URL=reids:3679
        depends_on:
            redis
